services:
  audio-converter:
    env_file:
      - .env
    build: .
    ports:
      - "127.0.0.1:9001:9001"
    networks:
      - supabase_default
    volumes:
      - /tmp:/tmp

networks:
  supabase:
    external: true